language: go
go:
  - 1.5
install: true
script:
  - export GO15VENDOREXPERIMENT=1
  - go get -u github.com/golang/lint/golint
  - go install github.com/golang/lint/golint
  - make lint
  - go vet $(go list ./... 2>/dev/null | grep -v /vendor/)
  - cd libkbfs && go test -i && go test -c && ./libkbfs.test -test.timeout 4m
  - cd ../bserver && go test -i && go test -c && ./bserver.test -test.timeout 4m
  - cd ../mdserver && go test -i && go test -c -tags integration && ./mdserver.test -test.timeout 4m
  # run libkbfs test suite against the real mdserver
  # TODO: why does the below sometimes hang? uncomment when fixed
  #- cd mdserver && go build && { KBFS_BIND_ADDR=127.0.0.1:8125 ./mdserver 2> /dev/null & } && cd ../../libkbfs/ && KEYBASE_TEST_MDSERVER_ADDR=127.0.0.1:8125 go test && killall -9 mdserver
  - cd ../libfuse && go test -i && go test -c
  - cd ../test
  - go test -i && go test
  # TODO disable Ruby tests
  - make test
notifications:
  slack: keybase:WKlhs55Mb4am4obv1rNRg8P0

