sudo: required
language: go
go:
  - 1.5
install: true
services:
  - docker
before_install:
  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      export DEBIAN_FRONTEND=noninteractive;
      sudo apt-get update;
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine;
      sudo rm /usr/local/bin/docker-compose;
      curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose;
      chmod +x docker-compose;
      sudo mv docker-compose /usr/local/bin;
      docker login -e $CI_EMAIL -u $CI_USER -p $CI_PASS $CI_HOST;
      docker pull $CI_HOST/kbweb && docker tag $CI_HOST/kbweb kbweb;
      docker pull $CI_HOST/kbclient && docker tag $CI_HOST/kbclient kbclient;
    fi
script:
  - export GO15VENDOREXPERIMENT=1
  - go get -u github.com/golang/lint/golint
  - go install github.com/golang/lint/golint
  - make lint
  - go vet $(go list ./... 2>/dev/null | grep -v /vendor/)
  - cd libkbfs && go test -i && go test -c && ./libkbfs.test -test.timeout 4m
  - cd ../bserver && go test -i && go test -c && ./bserver.test -test.timeout 4m
  - go test -c -tags integration
  - cd ../mdserver && go test -i && go test -c -tags integration && ./mdserver.test -test.timeout 4m
  # make sure the service binaries and tools all build cleanly
  - cd ../bserver/bserver && go build
  - cd ../../mdserver/mdserver && go build
  - cd ../../mdserver/mdmerkle && go build
  - cd ../../mdserver/mdtool && go build
  # run libkbfs test suite against the real mdserver
  # TODO: why does the below sometimes hang? uncomment when fixed
  #- cd mdserver && go build && { KBFS_BIND_ADDR=127.0.0.1:8125 ./mdserver 2> /dev/null & } && cd ../../libkbfs/ && KEYBASE_TEST_MDSERVER_ADDR=127.0.0.1:8125 go test && killall -9 mdserver
  - cd ../../libfuse && go test -i && go test -c
  - cd ../test
  - go test -i && go test
  - go test -c -tags fuse
  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      cd ../kbfsdocker && ./build_dockers.sh >/dev/null && go test -i -tags docker && go test -c -tags docker && ./kbfsdocker.test -test.v -test.timeout 6m;
    else
      echo "Not pushing to Docker, because this isn't a push to master.";
    fi
notifications:
  slack: keybase:WKlhs55Mb4am4obv1rNRg8P0

