language: go
go:
  - 1.5
install:
  - cd ..
  - git clone git@github.com:keybase/client
  - cd client
  - GO15VENDOREXPERIMENT=1 go build ./...
  - cd ../kbfs
  - GO15VENDOREXPERIMENT=0 go get ./...
script:
  - GO15VENDOREXPERIMENT=0 go build ./...
  - go get -u github.com/golang/lint/golint
  - go install github.com/golang/lint/golint
  - make lint
  - go vet ./...
  - cd libkbfs && go get -t && go test
  - cd ../bserver && go get -t && go test
  - cd ../mdserver && go get -t && go test && go test -tags integration
  # run libkbfs test suite against the real mdserver
  - cd mdserver && go build && { KBFS_BIND_ADDR=127.0.0.1:8125 ./mdserver 2> /dev/null & } && cd ../../libkbfs/ && KEYBASE_TEST_MDSERVER_ADDR=127.0.0.1:8125 go test && killall -9 mdserver
  - cd ../libfuse && go get -t && go test -c
  - cd ../test
  - make test
notifications:
  slack: keybase:WKlhs55Mb4am4obv1rNRg8P0

